# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!


background_opacity 0.80


# The basic colors
foreground              #4A4E73
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #4A4E73

# Cursor colors
cursor                  #4A4E73
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #4A4E73

# Kitty window border colors
active_border_color     #4A4E73
inactive_border_color   #4A4E73
bell_border_color       #4A4E73

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #4A4E73
active_tab_background   #4A4E73
inactive_tab_foreground #4A4E73
inactive_tab_background #4A4E73
tab_bar_background      #4A4E73

# Colors for marks (marked text in the terminal)
mark1_foreground #4A4E73
mark1_background #4A4E73
mark2_foreground #4A4E73
mark2_background #4A4E73
mark3_foreground #4A4E73
mark3_background #4A4E73

# The 16 terminal colors

# black
color0 #cdd6f4
color8 #cdd6f4

# red
color1 #4A4E73
color9 #4A4E73

# green
color2  #4A4E73
color10 #4A4E73

# yellow
color3  #4A4E73
color11 #4A4E73

# blue
color4  #4A4E73
color12 #4A4E73

# magenta
color5  #4A4E73
color13 #4A4E73

# cyan
color6  #4A4E73
color14 #4A4E73

# white
color7  #4A4E73
color15 #4A4E73
